build:
  environment:
    php:
      version: 7.2
    mysql: true
    postgresql: false
    mongodb: false
    elasticsearch: false
    redis: false
    memcached: false
    neo4j: false
    rabbitmq: false

  dependencies:
    before:
      - mysql -uroot -e 'CREATE DATABASE test_db'

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run


filter:
  excluded_paths:
    - RoboFile.php
    - phpinsights.php
    - tests/*
checks:
  php:
    code_rating: true

tools:
  php_analyzer: true
  php_changetracking: true
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_cpd: true
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
