---

version: "3.7"

services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test

  php:
    image: edyan/php:7.2
    container_name: php
    volumes:
      - "./:/app"
    stdin_open: true
    tty: true

  adminer:
    image: edyan/adminer
    ports:
      - "8080:80"
